apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos
  template:
    metadata:
      labels:
        app: chaos
    spec:
      containers:
      - name: chaos
        image: serhatsdocker/chaos-app:v2
        imagePullPolicy: Never
        env:
        - name: TARGET_URL
          value: "http://app-service:8080"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-service
spec:
  selector:
    app: chaos
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005